
# include ./theme.conf

# BEGIN_KITTY_FONTS
# font_family      family="MonoLisa Lucius"
# font_family_monospace      Source Code Pro

font_family      Source Code Pro
font_size        13
# END_KITTY_FONTS

confirm_os_window_close 0

foreground #dddddd
background #000000

background_opacity 0.8

dim_opacity 0.9

term xterm-256color

wayland_titlebar_color system

copy_on_select yes

# Number of lines of history to keep in memory for scrolling back
scrollback_lines 20000

# Window management
map super+n             new_os_window
map super+w             close_window
map ctrl+alt+enter      new_os_window
map ctrl+shift+enter    new_window
map ctrl+shift+o        new_window
map ctrl+shift+d        close_window
map ctrl+shift+]        next_window
map ctrl+shift+[        previous_window

map shift+right         move_window right
map shift+left          move_window left
map shift+up            move_window up
map shift+down          move_window down

map ctrl+shift+right    neighboring_window right
map ctrl+shift+left     neighboring_window left
map ctrl+shift+up       neighboring_window  up
map ctrl+shift+down     neighboring_window down


# map ctrl+shift+space    enter_selection_mode
map ctrl+shift+f          toggle_maximized

mouse_enabled yes

# Miscellaneous
map ctrl+up      increase_font_size
map ctrl+down    decrease_font_size
map ctrl+shift+backspace restore_font_size
map ctrl+alt+s enter_selection_mode
map f1 new_window_with_cwd
