#!/bin/sh

wallpaper_dir="${HOME}/Pictures/background/"

while true; do
    #feh --recursive --bg-max ~/Pictures/background/wallpaper-cityscape-design-art-world-fantasy-futuristic-wallpapers.jpg
    #feh --recursive --bg-max ~/Pictures/background/d0753e7b32.jpg
    #feh --recursive --bg-max ~/Pictures/background/Konachan.com-2243-blood.png
    #feh --recursive --randomize --bg-max ~/Pictures/background/

    # Set FILE as scaled desktop background.
    # This will fill the whole background, but the images' aspect ratio may not be preserved.
    feh --recursive --randomize --bg-scale ~/Pictures/background/
    sleep 30
done
