exec-once = ~/.config/hypr/scripts/checkupdates.sh

# wallpaper, Bar
# 动态壁纸
# exec-once = ~/.config/hypr/scripts/background-waly.sh

# 静态壁纸
exec-once = hyprpaper
# exec-once = ~/.config/hypr/scripts/background-static.sh

exec-once = waybar

# Input method
exec-once = fcitx5 --replace -d

# Screen shot
exec-once = flameshot

# Bluetooth, network, notifiction
exec-once = blueman-applet
exec-once = nm-applet
exec-once = swaync

# exec-once = browserpass
