wallpaper {
    monitor =
    # path = ~/Pictures/background
    # path = ~/Pictures/background/【4K】027-05_シェフィ（サマー）_Sub.jpg
    
    # path = ~/.config/wallpapers/space.png
    
    path = ~/Pictures/wallpapers/space.png
    # path = ~/Pictures/wallpapers/373.png
    # path = ~/Pictures/wallpapers/cool.jpg
    # path = ~/Pictures/wallpapers/wheat.png
    # path = ~/Pictures/wallpapers/skies.png
    # timeout = 60
}
splash = false 
